import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from 'shak/styles/Home.module.css'
import styled from 'styled-components'

const inter = Inter({ subsets: ['latin'] })

const Test = styled.div`
background-color: black;
color: white;
`

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Test>
        BIG POES
      </Test>
    </>
  )
}
